version: '3'

# Required env variables:
#
# - DB_USER
# - DB_PASSWORD
#
# Optional env variables:
#
# - PLUTO_TEST

services:
  webapp:
    container_name: web_app
    image: server:latest
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"

  pluto_pg:
    container_name: pluto_pg
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pluto_db_bootstrap:
    container_name: pluto_db_bootstrap
    image: db-bootstrap:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PLUTO_TEST: ${PLUTO_TEST:-true}
    restart: on-failure
    depends_on:
      - pluto_pg
    networks:
      - postgres
    links:
      - pluto_pg

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
