on:
  push:
    paths:
      - frontend/**
      - .github/workflows/frontend-check.yaml
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: E2E tests
        run: make -C frontend ci/check
